language: php
php:
  - 5.3
services:
  - mysql
before_script:
  - mysql -e 'DROP DATABASE IF EXISTS forum_test'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS forum_test'
  - sed -e "s/db_user=forum/db_user=\"root\"/" -e "s/db_pass=forum/db_pass=\"\"/" ./src/App/Config/Config.ini.sample > ./src/App/Config/Config.ini

script: phpunit .
