language: php
php:
  - 5.3
before_script:
  - mysql -e 'DROP DATABASE IF EXISTS forum_test'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS forum_test'
  - mysql -e 'GRANT ALL PRIVILEGES ON forum_test.* TO forum IDENTIFIED BY "forum"'
  - cp ./src/App/Config/Config.ini.sample ./src/App/Config/Config.ini
script: phpunit .
